# Generated by Django 4.2 on 2023-07-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_review_owner_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created"]},
        ),
    ]
