# Generated by Django 4.2 on 2023-06-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="social_youtube",
            new_name="social_stackoverflow",
        ),
    ]
