# Generated by Django 4.2 on 2023-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_social_youtube_profile_social_stackoverflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/avatar.svg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
